version: '3.8'

services:
  pulp-hugging-face:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "24817:24817"
    environment:
      - PULP_DB_ENGINE=django.db.backends.postgresql
      - PULP_DB_NAME=pulp
      - PULP_DB_USER=pulp
      - PULP_DB_PASSWORD=pulp
      - PULP_DB_HOST=postgres
      - PULP_DB_PORT=5432
      - PULP_REDIS_URL=redis://redis:6379
      - PULP_ALLOWED_HOSTS=*
      - PULP_SECRET_KEY=your-secret-key-here
    volumes:
      - pulp_data:/var/lib/pulp
    depends_on:
      - postgres
      - redis
    command: >
      bash -c "
        pulp-manager migrate &&
        pulp-manager collectstatic --noinput &&
        pulp-manager runserver 0.0.0.0:24817
      "

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=pulp
      - POSTGRES_USER=pulp
      - POSTGRES_PASSWORD=pulp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PULP_DB_ENGINE=django.db.backends.postgresql
      - PULP_DB_NAME=pulp
      - PULP_DB_USER=pulp
      - PULP_DB_PASSWORD=pulp
      - PULP_DB_HOST=postgres
      - PULP_DB_PORT=5432
      - PULP_REDIS_URL=redis://redis:6379
    volumes:
      - pulp_data:/var/lib/pulp
    depends_on:
      - postgres
      - redis
    command: pulp-worker

volumes:
  pulp_data:
  postgres_data:
  redis_data:
